version: 2.1

orbs:

executors:
  default:

# commands:

jobs:
  build:
    executor: default
    steps:
    - checkout
    -


workflows:
  version: 2
  # build-and-test:
  deploy-dev:
    jobs:
    -
